import React from 'react';
import './TermsAndConditions.css';
import { FaCalendarAlt, FaInfoCircle } from 'react-icons/fa';
// import termsAndConditions from '../../assets/termsAndConditions.jpg';

const TermsAndConditions = () => {
  return (
    <div className="terms-container">
      <div className="terms-header">
        {/* <img src={termsAndConditions} alt="Terms and Conditions" className="terms-image" /> */}
        <h1>Terms and Conditions</h1>
        <div className="terms-meta">
          <div className="version-info">
            <span className="version-label">Version 1.1</span>
          </div>
          <div className="last-updated">
            <FaCalendarAlt />
            <span>Last Updated: 15th February, 2024</span>
          </div>
        </div>
      </div>

      <div className="terms-content">
        <div className="terms-notice">
          <FaInfoCircle />
          <p>This document is an electronic record and published in accordance with the provisions of the Information Technology Act 2000 and the rules thereunder and generated by a computer system and does not require any physical or digital signatures.</p>
        </div>

        <div className="terms-section">
          <h2>A. Platform Information</h2>
          <p>This website https://picknow.in/ (Website) and mobile application 'Picknow' (App) (Website and App collectively referred to as the "Platform") is operated and managed by the Company. The term Company shall collectively and individually refer to each company which operates and manages the Platform for undertaking retail business with respect to the respective cities. You can access the complete Company details here</p>
        </div>

        <div className="terms-section">
          <h2>B. Terms of Use</h2>
          <p>These terms of use, or "Terms," regulate how you use the Platform. The Company may also be referred to in these Terms as "Picknow," "We," "Us," or "Our," depending on the situation, and users of the Platform are referred to as "You," "Your," or "User." We are grateful for your faith in us. We uphold appropriate security standards in order to protect Your information and the transactions.</p>
        </div>

        <div className="terms-section">
          <h2>C. Agreement</h2>
          <p>Before using the Platform, please carefully read these Terms. You must remove the App and may not use the Products and Services (as defined below) on the Platform if You disagree with these Terms. You enter into a legally binding agreement with Picknow simply by using or accessing the Platform. By doing so, You agree to be bound by these Terms and all other Picknow policies (such as the Company's cancellation and refund policy and its published privacy policy, or "Privacy Policy"), as posted on the Platform and updated from time to time.</p>
        </div>

        <div className="terms-section">
          <h2>D. Amendments</h2>
          <p>Picknow is free to change or amend these Terms at any time. By using the "Last Updated" legend above, you can find out when these Terms were last updated. The most recent version of these Terms is always available on the Platform. You ought to go over the Platform's Terms on a frequent basis. You agree to these modifications if you keep using and accessing the Platform. Should You find that the amended Terms are unacceptable, You ought to stop using the Platform.</p>
        </div>

        <div className="terms-section">
          <h2>1. Products and Services</h2>
          <div className="subsection">
            <h3>1.1. Platform Offerings</h3>
            <p>You agree that the Platform enables You to buy/get the following Products/Services:</p>
            <ul>
              <li>Personal, limited, non-exclusive access to buy products for personal consumption</li>
              <li>Quick and effective customer support for account and product queries</li>
            </ul>
          </div>
        </div>

        {/* Continue with other sections following the same pattern */}
        
        <div className="terms-section">
          <h2>10. Intellectual Property Rights</h2>
          <div className="subsection">
            <h3>10.1. Platform Content</h3>
            <p>The Platform and its processes, including text, videos, graphics, user interfaces, visual interfaces, sounds and music (if any), artwork, and computer code (and any combinations thereof) (collectively, the "Content") on the Platform are licenced to the Company.</p>
            
            <h3>10.2. Trademarks</h3>
            <p>The Platform's trademarks, logos, and service marks ("Marks") are either licenced by the Company or owned by third parties.</p>
            
            <h3>10.3. Product Rights</h3>
            <p>The Company does not claim ownership of any intellectual property rights related to the Products.</p>
            
            <h3>10.4. Third-Party References</h3>
            <p>References to third-party names, marks, services, or goods on the Platform are provided with their express consent for your convenience and do not imply endorsement, sponsorship, or recommendation.</p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default TermsAndConditions; 